/**
 * Row shapes as the database defines them.
 *
 * These mirror `supabase/schema.sql` exactly: snake_case identifiers, lowercase
 * enum labels, flat `*_min` / `*_max` / `*_open_ended` ranges, integer whole
 * dollars. Nothing here is shaped for the UI's convenience — see
 * `docs/DATA_MODEL.md`.
 *
 * The repository layer is the only place allowed to consume these. It
 * translates them to the camelCase domain types in `types.ts` exactly once, so
 * snake_case never reaches a component.
 */

/** `flexibility` enum. Display capitalisation is a presentation concern. */
export type Flexibility = "anywhere" | "remote" | "local";

/** `research_kind` enum. Note `data_study`, not "Data Study". */
export type ResearchKind = "report" | "guide" | "data_study";

export type ListingStatus = "available" | "under_offer" | "sold" | "withdrawn";

/**
 * Canonical category slugs. These appear in URLs, so a client that invents its
 * own spelling produces dead links — `ecommerce`, not `e-commerce`.
 */
export type CategorySlug = "online" | "service" | "ecommerce" | "local" | "creative";

export interface CategoryRow {
  slug: CategorySlug;
  label: string;
  description: string;
  sort_order: number;
}

/**
 * Keys of the weighted factors, matching `scoring_factors.key`.
 *
 * `scalability` and `competition` columns still hold data but are no longer
 * scored — see src/lib/scoring-model.ts and migration 0002.
 */
export type ScoringFactorKey =
  | "profit_potential"
  | "startup_cost"
  | "time_to_revenue"
  | "demand"
  | "flexibility";

export interface ScoringFactorRow {
  key: ScoringFactorKey;
  label: string;
  description: string;
  weight: number;
  sort_order: number;
}

export interface OpportunityStepRow {
  position: number;
  title: string;
  detail: string;
}

export interface OpportunityRow {
  slug: string;
  name: string;
  tagline: string;
  icon: string;
  category_slug: CategorySlug;

  startup_cost_min: number;
  startup_cost_max: number;
  startup_cost_open_ended: boolean;
  monthly_profit_min: number;
  monthly_profit_max: number;
  monthly_profit_open_ended: boolean;

  hours_per_week_min: number;
  hours_per_week_max: number;

  flexibility: Flexibility;
  summary: string;

  factor_demand: number;
  factor_profit_potential: number;
  factor_startup_cost: number;
  factor_time_to_revenue: number;
  factor_scalability: number;
  factor_competition: number;

  /**
   * Generated by the database, never written by a client. The fixture adapter
   * supplies it in place of Postgres until Phase 2; see `repository.ts`.
   */
  overall_score: number;

  skills: string[];
  pros: string[];
  cons: string[];
  tools: string[];
  steps: OpportunityStepRow[];

  /** Editorial review date, not a row modification timestamp. */
  reviewed_at: string;
}

export interface BusinessListingRow {
  slug: string;
  name: string;
  industry: string;
  location: string;
  asking_price: number;
  annual_revenue: number;
  /** Constrained `> 0` by the schema, so the multiple can never divide by zero. */
  cash_flow: number;
  established_year: number;
  employee_count: number;
  owner_financing: boolean;
  reason_for_sale: string;
  highlights: string[];
  status: ListingStatus;
  reviewed_at: string;
}

export interface FranchiseRow {
  slug: string;
  name: string;
  industry: string;
  franchise_fee: number;
  total_investment_min: number;
  total_investment_max: number;
  /** Free text: real systems quote "6% of gross" or "5.5% + 2% marketing". */
  royalty: string;
  liquid_capital_required: number;
  unit_count: number;
  founded_year: number;
  summary: string;
  support: string[];
  reviewed_at: string;
}

export interface FundingProgramRow {
  slug: string;
  name: string;
  funding_type: string;
  amount_min: number;
  amount_max: number;
  /** Free text: "Prime + 2.25% to 4.75%", "Factor 1.15x - 1.45x". */
  typical_rate: string;
  speed: string;
  /** Null means not underwritten on a credit score at all — not a low threshold. */
  min_credit_score: number | null;
  time_in_business: string;
  best_for: string;
  summary: string;
  requirements: string[];
  reviewed_at: string;
}

export interface ResearchPieceRow {
  slug: string;
  title: string;
  kind: ResearchKind;
  excerpt: string;
  /** Null while takeaways publish ahead of the full write-up. That is normal. */
  body: string | null;
  takeaways: string[];
  reading_time_minutes: number;
  published_at: string;
}
